/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Phase
 */
export interface Phase {
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  order: number;
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  type?: string;
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  tournament_id: number;
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  number_of_rounds: number;
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  best_of: number;
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  criteria: string | null;
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  started_at: string | null;
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  ended_at: string | null;
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  updated_at?: string;
}
