/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Player } from "./player";
// May contain unused imports in some cases
// @ts-ignore
import type { Round } from "./round";

/**
 *
 * @export
 * @interface PhaseDetails
 */
export interface PhaseDetails {
  /**
   *
   * @type {number}
   * @memberof PhaseDetails
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PhaseDetails
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof PhaseDetails
   */
  order: number;
  /**
   *
   * @type {string}
   * @memberof PhaseDetails
   */
  type?: string;
  /**
   *
   * @type {number}
   * @memberof PhaseDetails
   */
  tournament_id: number;
  /**
   *
   * @type {number}
   * @memberof PhaseDetails
   */
  number_of_rounds: number;
  /**
   *
   * @type {number}
   * @memberof PhaseDetails
   */
  best_of: number;
  /**
   *
   * @type {string}
   * @memberof PhaseDetails
   */
  criteria: string | null;
  /**
   *
   * @type {string}
   * @memberof PhaseDetails
   */
  started_at: string | null;
  /**
   *
   * @type {string}
   * @memberof PhaseDetails
   */
  ended_at: string | null;
  /**
   *
   * @type {string}
   * @memberof PhaseDetails
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof PhaseDetails
   */
  updated_at?: string;
  /**
   *
   * @type {Array<Player>}
   * @memberof PhaseDetails
   */
  players: Array<Player>;
  /**
   *
   * @type {Array<Round>}
   * @memberof PhaseDetails
   */
  rounds: Array<Round>;
}
