/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Pokemon
 */
export interface Pokemon {
  /**
   *
   * @type {number}
   * @memberof Pokemon
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  nickname?: string | null;
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  ability: string;
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  tera_type: string;
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  nature: string;
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  held_item: string | null;
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  move1: string | null;
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  move2: string | null;
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  move3: string | null;
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  move4: string | null;
}
