/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Round
 */
export interface Round {
  /**
   *
   * @type {number}
   * @memberof Round
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof Round
   */
  phase_id: number;
  /**
   *
   * @type {number}
   * @memberof Round
   */
  round_number: number;
  /**
   *
   * @type {string}
   * @memberof Round
   */
  started_at: string | null;
  /**
   *
   * @type {string}
   * @memberof Round
   */
  ended_at: string | null;
}
