/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserDetails
 */
export interface UserDetails {
  /**
   *
   * @type {string}
   * @memberof UserDetails
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof UserDetails
   */
  pronouns: string;
  /**
   *
   * @type {string}
   * @memberof UserDetails
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof UserDetails
   */
  first_name: string;
  /**
   *
   * @type {string}
   * @memberof UserDetails
   */
  last_name: string;
  /**
   *
   * @type {number}
   * @memberof UserDetails
   */
  id: number;
}
