/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserPostRequest
 */
export interface UserPostRequest {
  /**
   *
   * @type {string}
   * @memberof UserPostRequest
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof UserPostRequest
   */
  pronouns: string;
  /**
   *
   * @type {string}
   * @memberof UserPostRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof UserPostRequest
   */
  first_name: string;
  /**
   *
   * @type {string}
   * @memberof UserPostRequest
   */
  last_name: string;
  /**
   *
   * @type {number}
   * @memberof UserPostRequest
   */
  id?: number;
  /**
   * Must be at least 8 characters
   * @type {string}
   * @memberof UserPostRequest
   */
  password: string;
  /**
   * Must match the password.
   * @type {string}
   * @memberof UserPostRequest
   */
  password_confirmation: string;
}
