##
## DEVELOPMENT IMAGE
##
FROM thatguyinabeanie/battle-stadium:development-base-latest AS development
ENV RAILS_ENV=development
COPY app bin config db lib public storage Rakefile vendor config.ru .ruby-version /workspaces/$USERNAME/
RUN bundle check || bundle install
CMD ["rails", "server", "-b", "0.0.0.0"]
