services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fuecoco-db-dev
    ports:
      - 5432:5432

  # BATTLE STADIUM RAILS APP CONTAINER
  dev:
    environment:
      HOST_ENVIRONMENT: container
      DB_HOST: db
    build:
      context: .
      cache_from:
        - thatguyinabeanie/battle-stadium:dev-latest
      target: development
      dockerfile: Dockerfile
      tags:
        - thatguyinabeanie/battle-stadium:dev-latest
    command: >
      bash -c "
        rm -f tmp/pids/server.pid && \
        pnpm install --silent && \
        sleep infinity
      "
    tty: true
    ports:
      - 3000:3000
      - 8080:8080
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/up" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    volumes:
      - .:/battle-stadium
      - .zshrc:/root/.zshrc
      - turbo:/battle-stadium/.turbo
      - pnpm-store:/battle-stadium/.pnpm-store
volumes:
  postgres-data:
  turbo:
  pnpm-store:
