# nosonar
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:22 AS nextjs

RUN mkdir -p /workspaces/nextjs

# Set the working directory
WORKDIR /workspaces/nextjs

# Install dependencies
COPY nextjs/package.json .
COPY nextjs/package-lock.json .

RUN npm ci --silent --ignore-scripts

# Copy the source code
COPY nextjs /workspaces/nextjs

WORKDIR /workspaces/nextjs
# Expose the Next.js development server port

EXPOSE 8080

# Start the development server
CMD ["npm", "run", "dev"]
