source 'https://rubygems.org'

# Specify your Ruby version
ruby '3.3.4'

# Rails framework
gem 'rails', '~> 7.1'
gem 'active_model_serializers', '~> 0'
gem 'bcrypt', '~> 3'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'cancancan', '~> 3'
gem 'devise', '~> 4.9'
gem 'devise-jwt', '~> 0'
gem 'devise_token_auth', '~> 1'
gem 'faker', '~> 3'
gem 'hirb'
gem 'importmap-rails', '~> 2'
gem 'irb'
gem 'jbuilder', '~> 2'
gem 'jsonapi-serializer', '~> 2'
gem 'kredis', '~> 1'
gem 'omniauth-discord', '~> 1'
gem 'omniauth-rails_csrf_protection', '~> 1'
gem 'openssl', '~> 3.2'
gem 'pg', '~> 1.5.7'
gem 'puma', '~> 6.0'
gem 'rack-attack', '~> 6'
gem 'rack-cors', '~> 2'
gem 'rb-readline'
gem 'redis', '~> 5'
gem 'rswag-api'
gem 'rswag-ui'
gem 'ruby-lsp'
gem 'sidekiq', '~> 7'
gem 'sprockets-rails'
gem 'stimulus-rails', '~> 1'
gem 'turbo-rails', '~> 2'
gem 'tzinfo-data', platforms: %i[windows jruby]
gem 'versionist', '~> 2'

group :development do
  gem 'rails-erd'
  gem 'web-console', '~> 4'
end

group :test do
  gem 'brakeman', '~> 6', require: false
  gem 'bundler-audit', '~> 0'
  gem 'factory_bot_rails', '~> 6'
  gem 'rails-controller-testing', '~> 1'
  gem 'rspec_junit_formatter', '~> 0'
  gem 'ruby_audit', '~> 2', require: false
  gem 'selenium-webdriver', '~> 4', require: false
  gem 'shoulda-matchers', '~> 6'
  gem 'timecop', '~> 0'
end

# For documentation and testing your API
group :development, :test do
  gem 'debug', '~> 1'
  gem 'dotenv-rails'
  gem 'listen', '~> 3.3'
  gem 'rspec-json_expectations'
  gem 'rspec-rails'
  gem 'rswag-specs'
  gem 'ruby-lsp-rails', '~> 0.3.11'
  gem 'ruby-lsp-rspec'
  gem 'spring', '~> 4'
  gem 'traceroute', '~> 0'
  gem 'webmock', '~> 3'
end

group :development, :test, :rubocop do
  gem 'rubocop'
  gem 'rubocop-checkstyle_formatter'
  gem 'rubocop-erb'
  gem 'rubocop-factory_bot'
  gem 'rubocop-git'
  gem 'rubocop-graphql'
  gem 'rubocop-i18n'
  gem 'rubocop-junit-formatter'
  gem 'rubocop-md'
  gem 'rubocop-migrations'
  gem 'rubocop-packaging'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rails_config'
  gem 'rubocop-rails_deprecation'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'rubocop-rspec_rails'
  gem 'rubocop-rubycw'
  gem 'rubocop-shopify'
  gem 'rubocop-thread_safety'
end
